name: CI

on:
  push:
    branches:
      - master
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn
      - name: Run tests
        run: yarn test
  semantic_release:
    needs: tests
    name: semantic_release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v1
    - name: Run semantic release
      env: # Or as an environment variable
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        NPM_TOKEN: ${{secrets.NPM_TOKEN}} 
      run: |
        npm run typecheck
        npx semantic-release